"""Cambios en auth identity

Revision ID: c42ada694ca0
Revises: 
Create Date: 2025-11-11 22:55:36.189824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c42ada694ca0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_identity', sa.Column('auth0_sub', sa.Text(), nullable=True))
    op.drop_index('auth_identity_provider_idx', table_name='auth_identity')
    op.drop_constraint('auth_identity_provider_provider_user_id_key', 'auth_identity', type_='unique')
    op.drop_index('auth_identity_user_id_idx', table_name='auth_identity')
    op.create_index(op.f('ix_auth_identity_auth0_sub'), 'auth_identity', ['auth0_sub'], unique=True)
    op.create_index(op.f('ix_auth_identity_id'), 'auth_identity', ['id'], unique=False)
    op.create_index(op.f('ix_auth_identity_provider'), 'auth_identity', ['provider'], unique=False)
    op.create_index(op.f('ix_auth_identity_user_id'), 'auth_identity', ['user_id'], unique=False)
    op.create_unique_constraint('uq_provider_user_id', 'auth_identity', ['provider', 'provider_user_id'])
    op.alter_column('contribution_invites', 'subject_kind',
               existing_type=postgresql.ENUM('user', 'group', name='subject_type'),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('contribution_invites', 'status',
               existing_type=postgresql.ENUM('pending', 'accepted', 'declined', 'expired', name='invite_status'),
               type_=sa.Text(),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::invite_status"))
    op.drop_index('idx_invites_item', table_name='contribution_invites')
    op.create_index(op.f('ix_contribution_invites_id'), 'contribution_invites', ['id'], unique=False)
    op.create_index(op.f('ix_contribution_invites_item_id'), 'contribution_invites', ['item_id'], unique=False)
    op.create_index(op.f('ix_groups_id'), 'groups', ['id'], unique=False)
    op.create_index(op.f('ix_groups_owner_id'), 'groups', ['owner_id'], unique=False)
    op.alter_column('item_acl', 'subject_kind',
               existing_type=postgresql.ENUM('user', 'group', name='subject_type'),
               type_=sa.Text(),
               existing_nullable=False)
    op.drop_index('idx_item_acl_subject', table_name='item_acl')
    op.create_index(op.f('ix_item_acl_subject_id'), 'item_acl', ['subject_id'], unique=False)
    op.create_index(op.f('ix_item_acl_subject_kind'), 'item_acl', ['subject_kind'], unique=False)
    op.create_index(op.f('ix_item_activity_actor_id'), 'item_activity', ['actor_id'], unique=False)
    op.create_index(op.f('ix_item_activity_id'), 'item_activity', ['id'], unique=False)
    op.create_index(op.f('ix_item_activity_item_id'), 'item_activity', ['item_id'], unique=False)
    op.alter_column('item_claims', 'status',
               existing_type=postgresql.ENUM('interested', 'claimed', 'purchased', 'released', 'cancelled', name='claim_status'),
               type_=sa.Text(),
               existing_nullable=False)
    op.drop_index('idx_item_claims_item', table_name='item_claims')
    op.drop_constraint('item_claims_item_id_user_id_key', 'item_claims', type_='unique')
    op.create_index(op.f('ix_item_claims_id'), 'item_claims', ['id'], unique=False)
    op.create_index(op.f('ix_item_claims_item_id'), 'item_claims', ['item_id'], unique=False)
    op.create_index(op.f('ix_item_claims_user_id'), 'item_claims', ['user_id'], unique=False)
    op.create_unique_constraint('uq_item_claim', 'item_claims', ['item_id', 'user_id'])
    op.drop_index('idx_contrib_item', table_name='item_contributions')
    op.drop_constraint('item_contributions_item_id_user_id_key', 'item_contributions', type_='unique')
    op.create_index(op.f('ix_item_contributions_id'), 'item_contributions', ['id'], unique=False)
    op.create_index(op.f('ix_item_contributions_item_id'), 'item_contributions', ['item_id'], unique=False)
    op.create_index(op.f('ix_item_contributions_user_id'), 'item_contributions', ['user_id'], unique=False)
    op.create_unique_constraint('uq_item_contribution', 'item_contributions', ['item_id', 'user_id'])
    op.drop_index('idx_items_wishlist', table_name='items')
    op.create_index(op.f('ix_items_id'), 'items', ['id'], unique=False)
    op.create_index(op.f('ix_items_wishlist_id'), 'items', ['wishlist_id'], unique=False)
    op.create_index(op.f('ix_sessions_id'), 'sessions', ['id'], unique=False)
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_index(op.f('ix_tags_id'), 'tags', ['id'], unique=False)
    op.alter_column('users', 'display_name',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.alter_column('wishlist_permissions', 'subject_kind',
               existing_type=postgresql.ENUM('user', 'group', name='subject_type'),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('wishlist_permissions', 'role',
               existing_type=postgresql.ENUM('owner', 'editor', 'viewer', name='list_role'),
               type_=sa.Text(),
               existing_nullable=False,
               existing_server_default=sa.text("'viewer'::list_role"))
    op.drop_index('idx_wishlist_permissions_subject', table_name='wishlist_permissions')
    op.drop_constraint('wishlist_permissions_wishlist_id_subject_kind_subject_id_key', 'wishlist_permissions', type_='unique')
    op.create_index(op.f('ix_wishlist_permissions_id'), 'wishlist_permissions', ['id'], unique=False)
    op.create_index(op.f('ix_wishlist_permissions_subject_id'), 'wishlist_permissions', ['subject_id'], unique=False)
    op.create_index(op.f('ix_wishlist_permissions_subject_kind'), 'wishlist_permissions', ['subject_kind'], unique=False)
    op.create_index(op.f('ix_wishlist_permissions_wishlist_id'), 'wishlist_permissions', ['wishlist_id'], unique=False)
    op.create_unique_constraint('uq_wishlist_permission', 'wishlist_permissions', ['wishlist_id', 'subject_kind', 'subject_id'])
    op.create_index(op.f('ix_wishlists_creator_id'), 'wishlists', ['creator_id'], unique=False)
    op.create_index(op.f('ix_wishlists_id'), 'wishlists', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wishlists_id'), table_name='wishlists')
    op.drop_index(op.f('ix_wishlists_creator_id'), table_name='wishlists')
    op.drop_constraint('uq_wishlist_permission', 'wishlist_permissions', type_='unique')
    op.drop_index(op.f('ix_wishlist_permissions_wishlist_id'), table_name='wishlist_permissions')
    op.drop_index(op.f('ix_wishlist_permissions_subject_kind'), table_name='wishlist_permissions')
    op.drop_index(op.f('ix_wishlist_permissions_subject_id'), table_name='wishlist_permissions')
    op.drop_index(op.f('ix_wishlist_permissions_id'), table_name='wishlist_permissions')
    op.create_unique_constraint('wishlist_permissions_wishlist_id_subject_kind_subject_id_key', 'wishlist_permissions', ['wishlist_id', 'subject_kind', 'subject_id'], postgresql_nulls_not_distinct=False)
    op.create_index('idx_wishlist_permissions_subject', 'wishlist_permissions', ['subject_kind', 'subject_id'], unique=False)
    op.alter_column('wishlist_permissions', 'role',
               existing_type=sa.Text(),
               type_=postgresql.ENUM('owner', 'editor', 'viewer', name='list_role'),
               existing_nullable=False,
               existing_server_default=sa.text("'viewer'::list_role"))
    op.alter_column('wishlist_permissions', 'subject_kind',
               existing_type=sa.Text(),
               type_=postgresql.ENUM('user', 'group', name='subject_type'),
               existing_nullable=False)
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint('users_email_key', 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'display_name',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_index(op.f('ix_tags_id'), table_name='tags')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_id'), table_name='sessions')
    op.drop_index(op.f('ix_items_wishlist_id'), table_name='items')
    op.drop_index(op.f('ix_items_id'), table_name='items')
    op.create_index('idx_items_wishlist', 'items', ['wishlist_id'], unique=False)
    op.drop_constraint('uq_item_contribution', 'item_contributions', type_='unique')
    op.drop_index(op.f('ix_item_contributions_user_id'), table_name='item_contributions')
    op.drop_index(op.f('ix_item_contributions_item_id'), table_name='item_contributions')
    op.drop_index(op.f('ix_item_contributions_id'), table_name='item_contributions')
    op.create_unique_constraint('item_contributions_item_id_user_id_key', 'item_contributions', ['item_id', 'user_id'], postgresql_nulls_not_distinct=False)
    op.create_index('idx_contrib_item', 'item_contributions', ['item_id'], unique=False)
    op.drop_constraint('uq_item_claim', 'item_claims', type_='unique')
    op.drop_index(op.f('ix_item_claims_user_id'), table_name='item_claims')
    op.drop_index(op.f('ix_item_claims_item_id'), table_name='item_claims')
    op.drop_index(op.f('ix_item_claims_id'), table_name='item_claims')
    op.create_unique_constraint('item_claims_item_id_user_id_key', 'item_claims', ['item_id', 'user_id'], postgresql_nulls_not_distinct=False)
    op.create_index('idx_item_claims_item', 'item_claims', ['item_id'], unique=False)
    op.alter_column('item_claims', 'status',
               existing_type=sa.Text(),
               type_=postgresql.ENUM('interested', 'claimed', 'purchased', 'released', 'cancelled', name='claim_status'),
               existing_nullable=False)
    op.drop_index(op.f('ix_item_activity_item_id'), table_name='item_activity')
    op.drop_index(op.f('ix_item_activity_id'), table_name='item_activity')
    op.drop_index(op.f('ix_item_activity_actor_id'), table_name='item_activity')
    op.drop_index(op.f('ix_item_acl_subject_kind'), table_name='item_acl')
    op.drop_index(op.f('ix_item_acl_subject_id'), table_name='item_acl')
    op.create_index('idx_item_acl_subject', 'item_acl', ['subject_kind', 'subject_id'], unique=False)
    op.alter_column('item_acl', 'subject_kind',
               existing_type=sa.Text(),
               type_=postgresql.ENUM('user', 'group', name='subject_type'),
               existing_nullable=False)
    op.drop_index(op.f('ix_groups_owner_id'), table_name='groups')
    op.drop_index(op.f('ix_groups_id'), table_name='groups')
    op.drop_index(op.f('ix_contribution_invites_item_id'), table_name='contribution_invites')
    op.drop_index(op.f('ix_contribution_invites_id'), table_name='contribution_invites')
    op.create_index('idx_invites_item', 'contribution_invites', ['item_id'], unique=False)
    op.alter_column('contribution_invites', 'status',
               existing_type=sa.Text(),
               type_=postgresql.ENUM('pending', 'accepted', 'declined', 'expired', name='invite_status'),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::invite_status"))
    op.alter_column('contribution_invites', 'subject_kind',
               existing_type=sa.Text(),
               type_=postgresql.ENUM('user', 'group', name='subject_type'),
               existing_nullable=False)
    op.drop_constraint('uq_provider_user_id', 'auth_identity', type_='unique')
    op.drop_index(op.f('ix_auth_identity_user_id'), table_name='auth_identity')
    op.drop_index(op.f('ix_auth_identity_provider'), table_name='auth_identity')
    op.drop_index(op.f('ix_auth_identity_id'), table_name='auth_identity')
    op.drop_index(op.f('ix_auth_identity_auth0_sub'), table_name='auth_identity')
    op.create_index('auth_identity_user_id_idx', 'auth_identity', ['user_id'], unique=False)
    op.create_unique_constraint('auth_identity_provider_provider_user_id_key', 'auth_identity', ['provider', 'provider_user_id'], postgresql_nulls_not_distinct=False)
    op.create_index('auth_identity_provider_idx', 'auth_identity', ['provider'], unique=False)
    op.drop_column('auth_identity', 'auth0_sub')
    # ### end Alembic commands ###

